package brcparsers

// CustomBRCParserChatGPT parses a string representing a number with optional negative sign and returns the parsed integer value.
// this was generated by ChatGPT!
// It uses a for loop to iterate through each character in the input string, ignoring decimal points.
func CustomBRCParserChatGPT(input string) (int64, error) {
	// Variable to track if the number is negative
	var isNegativeNumber bool

	// Check if the input string starts with a negative sign
	if input[0] == '-' {
		isNegativeNumber = true
		// Remove the negative sign from the input
		input = input[1:]
	}

	// Variable to store the parsed integer value
	var output int64

	// Iterate through each character in the input string
	for _, char := range input {
		// Ignore decimal points
		if char == '.' {
			continue
		}
		// Convert character to integer and add it to the output value
		output = output*10 + int64(char-'0')
	}

	// If the number was negative, return the negation of the parsed value
	if isNegativeNumber {
		return -output, nil
	}

	// Otherwise, return the parsed value
	return output, nil
}
